### ISSUE TITLE
IndexError in junction detection part

### ISSUE THREAD

**Issue by liu-zhiyang** [FuyuLi/FLED#1]
I have tried to identify eccDNA from nanopore reads using FLED, but I got an error as shown as  following.
```shell
eccDNA Detection Begins !


2023-07-18 19:42:06: Parse SAinfo for continuous SA reads

Processed 100000 reads in 0.167 mins
Processed 200000 reads in 0.347 mins
Processed 300000 reads in 0.465 mins
Processed 400000 reads in 0.733 mins
Processed 500000 reads in 1.462 mins
Processed 600000 reads in 1.622 mins
Processed 700000 reads in 1.699 mins
Processed 800000 reads in 1.782 mins
Processed 900000 reads in 1.931 mins
Processed 1000000 reads in 2.097 mins
Processed 1100000 reads in 2.246 mins
Processed 1200000 reads in 2.405 mins
Processed 1300000 reads in 2.483 mins
Processed 1400000 reads in 2.648 mins
Processed 1500000 reads in 2.831 mins
Processed 1600000 reads in 3.009 mins
Processed 1700000 reads in 3.19 mins
Processed 1800000 reads in 3.345 mins
Processed 1900000 reads in 3.51 mins
Processed 2000000 reads in 3.663 mins
Processed 2100000 reads in 3.731 mins
Processed 2200000 reads in 3.895 mins
Processed 2300000 reads in 3.947 mins
Processed 2400000 reads in 3.969 mins
Processed 2500000 reads in 3.995 mins
Processed 2600000 reads in 4.137 mins
Processed 2700000 reads in 4.262 mins
Processed 2800000 reads in 4.417 mins
Processed 2900000 reads in 4.608 mins
Processed 3000000 reads in 4.804 mins
Processed 3100000 reads in 4.974 mins
Processed 3200000 reads in 5.111 mins
Processed 3300000 reads in 5.28 mins
Processed 3400000 reads in 5.54 mins
Processed 3500000 reads in 5.725 mins
Processed 3600000 reads in 5.893 mins
Processed 3700000 reads in 6.055 mins
Processed 3800000 reads in 6.227 mins
Processed 3900000 reads in 6.377 mins
Processed 4000000 reads in 6.557 mins
Processed 4100000 reads in 6.766 mins
Processed 4200000 reads in 6.96 mins
Processed 4300000 reads in 7.186 mins
Processed 4400000 reads in 7.373 mins
Processed 4500000 reads in 7.57 mins
Processed 4600000 reads in 7.705 mins
Processed 4700000 reads in 7.894 mins
Processed 4800000 reads in 8.063 mins
Processed 4900000 reads in 8.232 mins
Processed 5000000 reads in 8.402 mins
Processed 5100000 reads in 8.55 mins
Processed 5200000 reads in 8.77 mins
Processed 5300000 reads in 8.946 mins
Processed 5400000 reads in 9.112 mins
Processed 5500000 reads in 9.274 mins
Processed 5600000 reads in 9.449 mins
Processed 5700000 reads in 9.529 mins
Processed 5800000 reads in 9.68 mins
Processed 5900000 reads in 9.834 mins
Processed 6000000 reads in 10.004 mins
Processed 6100000 reads in 10.14 mins
Processed 6200000 reads in 10.234 mins
Processed 6300000 reads in 10.371 mins
Processed 6400000 reads in 10.653 mins
Processed 6500000 reads in 10.828 mins
Processed 6600000 reads in 11.017 mins
Processed 6700000 reads in 11.169 mins
Processed 6800000 reads in 11.233 mins
Processed 6900000 reads in 11.432 mins
Processed 7000000 reads in 11.618 mins
Processed 7100000 reads in 11.761 mins
Processed 7200000 reads in 11.937 mins
Processed 7300000 reads in 12.115 mins
Processed 7400000 reads in 12.298 mins
Processed 7500000 reads in 12.486 mins
Processed 7600000 reads in 12.671 mins
Processed 7700000 reads in 12.921 mins
Processed 7800000 reads in 13.079 mins
Processed 7900000 reads in 13.244 mins
Processed 8000000 reads in 13.4 mins
Processed 8100000 reads in 13.557 mins
Processed 8200000 reads in 13.721 mins
Processed 8300000 reads in 13.862 mins
Processed 8400000 reads in 14.042 mins
Processed 8500000 reads in 14.434 mins
Processed 8600000 reads in 14.51 mins
Processed 8700000 reads in 14.682 mins
Processed 8800000 reads in 14.884 mins
Processed 8900000 reads in 15.066 mins
Processed 9000000 reads in 15.24 mins
Processed 9100000 reads in 15.458 mins
Processed 9200000 reads in 15.664 mins
Processed 9300000 reads in 15.81 mins
Processed 9400000 reads in 16.147 mins
Processed 9500000 reads in 16.344 mins
Processed 9600000 reads in 16.366 mins

2023-07-18 19:58:28: Parse continuous SAinfo for junction detection

Traceback (most recent call last):
  File "/home/liuzhy/anaconda3/envs/nanoecc/bin/FLED", line 33, in <module>
    sys.exit(load_entry_point('FLED==1.5.0', 'console_scripts', 'FLED')())
  File "/home/liuzhy/anaconda3/envs/nanoecc/lib/python3.10/site-packages/FLED-1.5.0-py3.10.egg/FLED/longreadscircDNAdetection.py", line 196, in main
  File "/home/liuzhy/anaconda3/envs/nanoecc/lib/python3.10/site-packages/FLED-1.5.0-py3.10.egg/FLED/longreadscircDNAdetection.py", line 63, in __init__
  File "/home/liuzhy/anaconda3/envs/nanoecc/lib/python3.10/site-packages/FLED-1.5.0-py3.10.egg/FLED/ecDNAdetection.py", line 61, in run_detection
  File "/home/liuzhy/anaconda3/envs/nanoecc/lib/python3.10/site-packages/FLED-1.5.0-py3.10.egg/FLED/_utils.py", line 247, in parse_junction_from_SAinfo
IndexError: invalid index to scalar variable.
```

I am not familiar with python, so could you help me?

**Comment by MiguelFiguerooa** [comment]
Hi Liu did you manage to run FLED without the invalid index to scalar variable issue? Im experimenting the same problem
